# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/David/Processor/Processor.cache/wt [current_project]
set_property parent.project_path C:/Users/David/Processor/Processor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/David/Processor/Processor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/imports/new/FA1B.sv
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/imports/new/Logic.sv
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/imports/new/ALU1B.sv
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/new/Controller.sv
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/new/DataMemory.sv
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/imports/new/ALU128B.sv
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/new/SignExtender.sv
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/new/MUX2_1.sv
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/new/Counter.sv
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/new/InstructionMemory.sv
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/new/RegFile.sv
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/new/Processor.sv
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/imports/Final-Project/seg_display.sv
  C:/Users/David/Processor/Processor.srcs/sources_1/imports/sources_1/imports/Final-Project/basys3_wrapper.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/David/Processor/Processor.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/David/Processor/Processor.srcs/constrs_1/imports/Downloads/Basys3_Master.xdc]


synth_design -top basys3_wrapper -part xc7a35tcpg236-1


write_checkpoint -force -noxdef basys3_wrapper.dcp

catch { report_utilization -file basys3_wrapper_utilization_synth.rpt -pb basys3_wrapper_utilization_synth.pb }
